// Access-layer contract, run on every available backend (sqlite always, postgres when TEST_PG_URL is set).
import test from 'node:test';
import assert from 'node:assert/strict';
import { aiBoardBackend, toPgDdl, toPgPlaceholders, applyMigrations } from '../server/ai-board/db/index.js';
import { backends } from './support/ai-board-db.js';

test('backend switch defaults to sqlite and rejects junk', () => {
  assert.equal(aiBoardBackend({}), 'sqlite');
  assert.equal(aiBoardBackend({ AI_BOARD_DB: ' Postgres ' }), 'postgres');
  assert.throws(() => aiBoardBackend({ AI_BOARD_DB: 'mysql' }), /sqlite or postgres/);
});

test('placeholders skip quoted literals; ddl widens ints', () => {
  assert.equal(toPgPlaceholders("SELECT ? , '?' , ?"), "SELECT $1 , '?' , $2");
  assert.match(toPgDdl('id INTEGER PRIMARY KEY AUTOINCREMENT, g REAL, n INTEGER'),
    /BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, g DOUBLE PRECISION, n BIGINT/);
});

for (const backend of backends) {
  test(`[${backend.name}] migrations apply once, are re-runnable and create the board tables`, async () => {
    const d = await backend.open();
    try {
      const before = (await d.get('SELECT COUNT(*) AS n FROM schema_migrations')).n;
      assert.equal(before, 16);
      await applyMigrations(d);
      assert.equal((await d.get('SELECT COUNT(*) AS n FROM schema_migrations')).n, before);
      await d.get('SELECT * FROM ai_tickets LIMIT 1');
      await d.get('SELECT * FROM ai_post_merge_watch LIMIT 1');
    } finally { await d.dispose(); }
  });

  test(`[${backend.name}] insert returns id, tx commits and rolls back, 64-bit ms timestamps round-trip`, async () => {
    const d = await backend.open();
    try {
      const now = Date.now();
      const id = await d.insert(`INSERT INTO requests(domain, title, created_at, updated_at) VALUES (?, ?, ?, ?)`,
        ['pharmacy', 'tiêu đề', now, now]);
      assert.equal(typeof id, 'number');
      assert.equal((await d.get('SELECT created_at, COUNT(*) OVER () AS n FROM requests WHERE id = ?', [id])).created_at, now);
      await assert.rejects(d.tx(async (t) => {
        await t.run('UPDATE requests SET title = ? WHERE id = ?', ['đổi', id]);
        throw new Error('boom');
      }), /boom/);
      assert.equal((await d.get('SELECT title FROM requests WHERE id = ?', [id])).title, 'tiêu đề');
      await d.tx((t) => t.run('UPDATE requests SET title = ? WHERE id = ?', ['đổi', id]));
      assert.equal((await d.get('SELECT title FROM requests WHERE id = ?', [id])).title, 'đổi');
      const json = JSON.stringify({ budget_units: 12.5 });
      assert.equal(Number((await d.get(`SELECT ${d.jsonNum('CAST(? AS TEXT)', 'budget_units')} AS v`, [json])).v), 12.5);
    } finally { await d.dispose(); }
  });

  test(`[${backend.name}] root ticket status trigger keeps the request in step`, async () => {
    const d = await backend.open();
    try {
      const now = Date.now();
      const rid = await d.insert(`INSERT INTO requests(domain, title, created_at, updated_at) VALUES ('pharmacy', 'x', ?, ?)`, [now, now]);
      const tid = await d.insert(`INSERT INTO ai_tickets(source_request_id, sequence, kind, title, status, phase, created_at, updated_at)
        VALUES (?, 0, 'root', 'x', 'queued', 'intake', ?, ?)`, [rid, now, now]);
      await d.run(`UPDATE ai_tickets SET status = 'running', updated_at = ? WHERE id = ?`, [now + 5, tid]);
      assert.equal((await d.get('SELECT status FROM requests WHERE id = ?', [rid])).status, 'reviewing');
    } finally { await d.dispose(); }
  });
}
