// App db handle contract on every backend (sqlite always, postgres when TEST_PG_URL is set).
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import pg from 'pg';
import { bindParams, compileParams, createAppDb, pgDdl } from '../server/db-core.js';

const DDL = `
  CREATE TABLE IF NOT EXISTS t (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, n INTEGER NOT NULL DEFAULT 0, r REAL);
  CREATE TABLE IF NOT EXISTS kv (k TEXT NOT NULL, v TEXT, PRIMARY KEY (k));`;

const PG_URL = process.env.TEST_PG_URL || '';
if (!PG_URL) throw new Error('TEST_PG_URL required for PG-only tests');
const backends = [
  ...(PG_URL ? [{
    name: 'postgres',
    async open() {
      const schema = `t_${randomBytes(6).toString('hex')}`;
      const admin = new pg.Client({ connectionString: PG_URL });
      await admin.connect();
      await admin.query(`CREATE SCHEMA ${schema}`);
      const url = new URL(PG_URL);
      url.searchParams.set('options', `-c search_path=${schema}`);
      const db = createAppDb({ url: url.toString() });
      db.cleanup = async () => { await admin.query(`DROP SCHEMA ${schema} CASCADE`); await admin.end(); };
      return db;
    },
    async done(db) { await db.close(); await db.cleanup(); },
  }] : []),
];

test('compileParams: ? and @name in order, named reused, literals and casts untouched', () => {
  const c = compileParams(`SELECT '?', '@x', a::int FROM t WHERE a = ? AND b = @b AND c = @b AND d = ? -- ? @z`);
  assert.equal(c.sql, `SELECT '?', '@x', a::int FROM t WHERE a = $1 AND b = $2 AND c = $2 AND d = $3 -- ? @z`);
  assert.deepEqual(bindParams(c.slots, [10, { b: 'B' }, 30]), [10, 'B', 30]);
  assert.deepEqual(bindParams(compileParams('x=? AND y=?').slots, [[1, 2]]), [1, 2]);
  assert.throws(() => bindParams(compileParams('x=@q').slots, [{}]), /Missing named parameter/);
});

test('pgDdl: identity ids, wide ints, idempotent add column', () => {
  assert.match(pgDdl('ALTER TABLE t ADD COLUMN c INTEGER'), /ADD COLUMN IF NOT EXISTS c BIGINT/);
  assert.match(pgDdl('CREATE TABLE t (id INTEGER PRIMARY KEY AUTOINCREMENT, r REAL)'),
    /BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, r DOUBLE PRECISION/);
});

for (const b of backends) {
  test(`[${b.name}] prepare get/all/run, named + mixed params, lastInsertRowid, changes`, async () => {
    const db = await b.open();
    try {
      await db.exec(DDL);
      const ins = db.prepare('INSERT INTO t (name, n, r) VALUES (@name, @n, @r)');
      const a = await ins.run({ name: 'a', n: 1, r: 1.5 });
      const c = await ins.run({ name: 'c', n: 3, r: null });
      assert.equal(Number(a.lastInsertRowid), 1);
      assert.equal(Number(c.lastInsertRowid), 2);
      assert.equal(a.changes, 1);
      assert.deepEqual((await db.prepare('SELECT name FROM t WHERE n >= ? ORDER BY n LIMIT @lim').all(1, { lim: 5 })).map((r) => r.name), ['a', 'c']);
      assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM t').get()).n, 2);
      assert.equal((await db.prepare('SELECT r FROM t WHERE name = ?').get('a')).r, 1.5);
      assert.equal(await db.prepare('SELECT 1 FROM t WHERE name = ?').get('zzz'), undefined);
      assert.equal((await db.prepare('UPDATE t SET n = n + 1').run()).changes, 2);
      const kv = db.prepare('INSERT INTO kv (k, v) VALUES (?, ?) ON CONFLICT DO NOTHING');
      assert.equal((await kv.run('x', '1')).changes, 1);
      assert.equal((await kv.run('x', '2')).changes, 0);
    } finally { await b.done(db); }
  });

  test(`[${b.name}] transaction commits, rolls back, nests as savepoints, returns the value`, async () => {
    const db = await b.open();
    try {
      await db.exec(DDL);
      const add = db.transaction(async (name, fail) => {
        await db.prepare('INSERT INTO t (name) VALUES (?)').run(name);
        if (fail) throw new Error('boom');
        return name.toUpperCase();
      });
      assert.equal(await add('one'), 'ONE');
      await assert.rejects(add('two', true), /boom/);
      const outer = db.transaction(async () => {
        await add('three');
        await assert.rejects(add('four', true), /boom/); // inner rolls back to its savepoint only
        await db.prepare('INSERT INTO t (name) VALUES (?)').run('five');
      });
      await outer();
      assert.deepEqual((await db.prepare('SELECT name FROM t ORDER BY id').all()).map((r) => r.name), ['one', 'three', 'five']);
    } finally { await b.done(db); }
  });

  test(`[${b.name}] concurrent transactions do not interleave their statements`, async () => {
    const db = await b.open();
    try {
      await db.exec(DDL);
      await db.prepare('INSERT INTO kv (k, v) VALUES (?, ?)').run('c', '0');
      const bump = db.transaction(async () => {
        const row = await db.prepare('SELECT v FROM kv WHERE k = ?').get('c');
        await new Promise((r) => setTimeout(r, 5));
        await db.prepare('UPDATE kv SET v = ? WHERE k = ?').run(String(Number(row.v) + 1), 'c');
      });
      await Promise.all(Array.from({ length: 8 }, () => bump()));
      assert.equal((await db.prepare('SELECT v FROM kv WHERE k = ?').get('c')).v, '8');
    } finally { await b.done(db); }
  });
}
