// Async PostgreSQL contract (pool, ambient transactions, savepoints) shared by the app db handle and the AI board.
// SQL is written once with `?` placeholders and portable syntax (ON CONFLICT DO NOTHING, COALESCE, CAST); the few
// dialect gaps go through `d.jsonNum` / `d.lockRow` / `d.lockQueue(alias)`. `t` inside tx() has the same methods as `d`.
// Board schema migrations (server/ai-board/migrations, PostgreSQL overrides in ./pg) run from db.js at boot.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AsyncLocalStorage } from 'node:async_hooks';
import pg from 'pg';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.join(HERE, '..', 'migrations');
const MIGRATION_LOCK = 7_000_101; // pg_advisory_xact_lock key: two app instances must not migrate at once

/** `?` -> `$n`, skipping quoted literals. */
export function toPgPlaceholders(sql) {
  let n = 0;
  let quoted = false;
  let out = '';
  for (const ch of sql) {
    if (ch === "'") quoted = !quoted;
    out += ch === '?' && !quoted ? `$${++n}` : ch;
  }
  return out;
}

/** SQLite DDL -> PostgreSQL DDL: identity ids, 64-bit ints (ms timestamps overflow int4), double floats. */
export function toPgDdl(sql) {
  return sql
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bINTEGER\b/g, 'BIGINT')
    .replace(/\bREAL\b/g, 'DOUBLE PRECISION');
}

const withInsertId = (sql) => `${sql.trim().replace(/;$/, '')} RETURNING id`;

/** Ambient transaction: code inside tx() may call d.get/run/... directly, they join the open transaction
 * (AsyncLocalStorage), and a nested tx() becomes a SAVEPOINT, like better-sqlite3 nested transactions. */
const ambient = new AsyncLocalStorage();
let savepointSeq = 0;
async function runTx(ops, exec, fn) {
  if (ambient.getStore()?.ops === ops) {
    const name = `sp_${++savepointSeq}`;
    await exec(`SAVEPOINT ${name}`);
    try {
      const value = await fn(ops);
      await exec(`RELEASE ${name}`);
      return value;
    } catch (error) {
      await exec(`ROLLBACK TO ${name}`);
      await exec(`RELEASE ${name}`);
      throw error;
    }
  }
  return null;
}
const joined = (base) => {
  const cur = () => ambient.getStore()?.base === base ? ambient.getStore().ops : base;
  return new Proxy(base, {
    get: (target, key) => (typeof target[key] === 'function' && ['get', 'all', 'run', 'insert', 'exec'].includes(key)
      ? (...a) => cur()[key](...a) : target[key]),
  });
};

function pgOps(q) {
  const call = (sql, p) => q.query(toPgPlaceholders(sql), p);
  return {
    dialect: 'postgres',
    lockRow: ' FOR UPDATE',
    lockQueue: (alias) => ` FOR UPDATE OF ${alias} SKIP LOCKED`,
    // dotted path ('pull_request.number') into the JSON text column; numeric / text result
    jsonNum: (col, path) => `(${col}::jsonb #>> '{${path.split('.').join(',')}}')::numeric`,
    jsonText: (col, path) => `(${col}::jsonb #>> '{${path.split('.').join(',')}}')`,
    async get(sql, p = []) { return (await call(sql, p)).rows[0]; },
    async all(sql, p = []) { return (await call(sql, p)).rows; },
    async run(sql, p = []) { return { changes: (await call(sql, p)).rowCount }; },
    async insert(sql, p = []) { return (await call(withInsertId(sql), p)).rows[0].id; },
    async exec(sql) { await q.query(sql); },
  };
}

/** url: postgres connection string. int8/numeric come back as JS numbers (ids and ms timestamps fit in 2^53). */
export function createPgDb({ url, max = 10 }) {
  const pool = new pg.Pool({
    connectionString: url, max,
    types: { getTypeParser: (oid, fmt) => (oid === 20 || oid === 1700 ? Number : pg.types.getTypeParser(oid, fmt)) },
  });
  // PG restart bắn 'error' trên client rảnh trong pool; không có listener thì process chết. Pool tự mở client mới ở query sau.
  pool.on('error', (error) => console.error(`[ai-board/db] pg pool idle client error: ${error.message}`));
  const base = { ...pgOps(pool), pool, async close() { await pool.end(); } };
  base.tx = async (fn) => {
    const store = ambient.getStore();
    if (store?.base === base) return runTx(store.ops, (sql) => store.ops.exec(sql), fn);
    const client = await pool.connect();
    const ops = pgOps(client);
    try {
      await client.query('BEGIN');
      const value = await ambient.run({ base, ops }, () => fn(ops));
      await client.query('COMMIT');
      return value;
    } catch (error) {
      await client.query('ROLLBACK').catch(() => {});
      throw error;
    } finally {
      client.release();
    }
  };
  return joined(base);
}

/** Ordered, re-runnable: each file runs once in its own transaction with its schema_migrations row. */
export async function applyMigrations(d, migrationsDir = MIGRATIONS_DIR) {
  const pgSql = d.dialect === 'postgres';
  await d.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
    scope TEXT NOT NULL, version TEXT NOT NULL, applied_at ${pgSql ? 'BIGINT' : 'INTEGER'} NOT NULL,
    PRIMARY KEY(scope, version))`);
  for (const version of fs.readdirSync(migrationsDir).filter((n) => /^\d+.*\.sql$/.test(n)).sort()) {
    await d.tx(async (t) => {
      if (pgSql) await t.get('SELECT pg_advisory_xact_lock(?)', [MIGRATION_LOCK]);
      if (await t.get('SELECT 1 AS ok FROM schema_migrations WHERE scope = ? AND version = ?', ['ai-board', version])) return;
      let sql = fs.readFileSync(path.join(migrationsDir, version), 'utf8');
      if (pgSql) {
        const override = path.join(HERE, 'pg', version);
        sql = fs.existsSync(override) ? fs.readFileSync(override, 'utf8') : toPgDdl(sql);
      }
      await t.exec(sql);
      await t.run('INSERT INTO schema_migrations(scope, version, applied_at) VALUES (?, ?, ?)', ['ai-board', version, Date.now()]);
    });
  }
}
