// Async DB contract for the AI board: one interface, two backends (SQLite stays default, PostgreSQL is opt-in).
// SQL is written once with `?` placeholders and portable syntax (ON CONFLICT DO NOTHING, COALESCE, CAST); the few
// dialect gaps go through `d.jsonNum` / `d.forUpdate`. `t` inside tx() has the same methods as `d`.
//
// Backend switch: AI_BOARD_DB=sqlite|postgres (default sqlite) + AI_BOARD_DATABASE_URL for postgres.
// ROLLBACK: unset AI_BOARD_DB (or set sqlite) and restart. The SQLite file is not written while postgres is selected
// and PostgreSQL rows are not copied back, so rows created on PostgreSQL after the flip stay there.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = path.join(HERE, '..', 'migrations');
const MIGRATION_LOCK = 7_000_101; // pg_advisory_xact_lock key: two app instances must not migrate at once

export function aiBoardBackend(env = process.env) {
  const v = String(env.AI_BOARD_DB || 'sqlite').trim().toLowerCase();
  if (v !== 'sqlite' && v !== 'postgres') throw new Error(`AI_BOARD_DB must be sqlite or postgres, got "${v}"`);
  return v;
}

/** `?` -> `$n`, skipping quoted literals. */
export function toPgPlaceholders(sql) {
  let n = 0;
  let quoted = false;
  let out = '';
  for (const ch of sql) {
    if (ch === "'") quoted = !quoted;
    out += ch === '?' && !quoted ? `$${++n}` : ch;
  }
  return out;
}

/** SQLite DDL -> PostgreSQL DDL: identity ids, 64-bit ints (ms timestamps overflow int4), double floats. */
export function toPgDdl(sql) {
  return sql
    .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
    .replace(/\bINTEGER\b/g, 'BIGINT')
    .replace(/\bREAL\b/g, 'DOUBLE PRECISION');
}

const withInsertId = (sql) => `${sql.trim().replace(/;$/, '')} RETURNING id`;

function sqliteOps(raw) {
  return {
    dialect: 'sqlite',
    forUpdate: '',
    jsonNum: (col, key) => `json_extract(${col}, '$.${key}')`,
    async get(sql, p = []) { return raw.prepare(sql).get(...p); },
    async all(sql, p = []) { return raw.prepare(sql).all(...p); },
    async run(sql, p = []) { return { changes: raw.prepare(sql).run(...p).changes }; },
    async insert(sql, p = []) { return Number(raw.prepare(sql).run(...p).lastInsertRowid); },
    async exec(sql) { raw.exec(sql); },
  };
}

/** raw: a better-sqlite3 Database. One connection: tx() calls are serialised; a plain call from another task
 * while a tx is open joins it (ponytail: fine while the board is the only async caller). */
export function createSqliteDb(raw) {
  const ops = sqliteOps(raw);
  let chain = Promise.resolve();
  return {
    ...ops,
    raw,
    tx(fn) {
      const result = chain.then(async () => {
        raw.exec('BEGIN IMMEDIATE');
        try {
          const value = await fn(ops);
          raw.exec('COMMIT');
          return value;
        } catch (error) {
          raw.exec('ROLLBACK');
          throw error;
        }
      });
      chain = result.catch(() => {});
      return result;
    },
    async close() { raw.close(); },
  };
}

function pgOps(q) {
  const call = (sql, p) => q.query(toPgPlaceholders(sql), p);
  return {
    dialect: 'postgres',
    forUpdate: ' FOR UPDATE',
    jsonNum: (col, key) => `(${col}::jsonb ->> '${key}')::numeric`,
    async get(sql, p = []) { return (await call(sql, p)).rows[0]; },
    async all(sql, p = []) { return (await call(sql, p)).rows; },
    async run(sql, p = []) { return { changes: (await call(sql, p)).rowCount }; },
    async insert(sql, p = []) { return (await call(withInsertId(sql), p)).rows[0].id; },
    async exec(sql) { await q.query(sql); },
  };
}

/** url: postgres connection string. int8/numeric come back as JS numbers (ids and ms timestamps fit in 2^53). */
export function createPgDb({ url, max = 10 }) {
  const pool = new pg.Pool({
    connectionString: url, max,
    types: { getTypeParser: (oid, fmt) => (oid === 20 || oid === 1700 ? Number : pg.types.getTypeParser(oid, fmt)) },
  });
  return {
    ...pgOps(pool),
    pool,
    async tx(fn) {
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        const value = await fn(pgOps(client));
        await client.query('COMMIT');
        return value;
      } catch (error) {
        await client.query('ROLLBACK').catch(() => {});
        throw error;
      } finally {
        client.release();
      }
    },
    async close() { await pool.end(); },
  };
}

/** Env -> db. SQLite needs the open better-sqlite3 handle (the app's existing one). */
export function openAiBoardDb({ env = process.env, sqlite } = {}) {
  if (aiBoardBackend(env) === 'sqlite') return createSqliteDb(sqlite);
  if (!env.AI_BOARD_DATABASE_URL) throw new Error('AI_BOARD_DATABASE_URL is required when AI_BOARD_DB=postgres');
  return createPgDb({ url: env.AI_BOARD_DATABASE_URL });
}

/** Stand-in for tables db.js owns (users, requests, request_messages) on a fresh PostgreSQL. Idempotent. */
export async function applyPgBaseSchema(d) {
  await d.exec(fs.readFileSync(path.join(HERE, 'pg', 'base.sql'), 'utf8'));
}

/** Ordered, re-runnable: each file runs once in its own transaction with its schema_migrations row. */
export async function applyMigrations(d, migrationsDir = MIGRATIONS_DIR) {
  const pgSql = d.dialect === 'postgres';
  await d.exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
    scope TEXT NOT NULL, version TEXT NOT NULL, applied_at ${pgSql ? 'BIGINT' : 'INTEGER'} NOT NULL,
    PRIMARY KEY(scope, version))`);
  for (const version of fs.readdirSync(migrationsDir).filter((n) => /^\d+.*\.sql$/.test(n)).sort()) {
    await d.tx(async (t) => {
      if (pgSql) await t.get('SELECT pg_advisory_xact_lock(?)', [MIGRATION_LOCK]);
      if (await t.get('SELECT 1 AS ok FROM schema_migrations WHERE scope = ? AND version = ?', ['ai-board', version])) return;
      let sql = fs.readFileSync(path.join(migrationsDir, version), 'utf8');
      if (pgSql) {
        const override = path.join(HERE, 'pg', version);
        sql = fs.existsSync(override) ? fs.readFileSync(override, 'utf8') : toPgDdl(sql);
      }
      await t.exec(sql);
      await t.run('INSERT INTO schema_migrations(scope, version, applied_at) VALUES (?, ?, ?)', ['ai-board', version, Date.now()]);
    });
  }
}
