-- Shared tables the AI board reads/writes but db.js (SQLite) still owns. Stand-in until the app moves to PostgreSQL:
-- same names and columns the board touches; widen only when the board starts using another column.
-- Projection of the app's users (SQLite stays authoritative; ids are shared, rows are upserted when a user is seen).
-- Identity starts far above any SQLite id so the board's own system user ('ai-board') can never collide with a real account.
CREATE TABLE IF NOT EXISTS users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000000000) PRIMARY KEY,
  username      TEXT   NOT NULL UNIQUE,
  display_name  TEXT   NOT NULL,
  password_hash TEXT   NOT NULL DEFAULT '',
  role          TEXT   NOT NULL DEFAULT 'student',
  enrolled_domain TEXT,
  email         TEXT,
  created_at    BIGINT NOT NULL DEFAULT 0,
  last_login    BIGINT
);
CREATE TABLE IF NOT EXISTS requests (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain      TEXT   NOT NULL,
  type        TEXT   NOT NULL DEFAULT 'other',
  title       TEXT   NOT NULL,
  detail      TEXT,
  student     TEXT   NOT NULL DEFAULT 'Ẩn danh',
  status      TEXT   NOT NULL DEFAULT 'pending',
  votes       BIGINT NOT NULL DEFAULT 1,
  admin_note  TEXT,
  created_at  BIGINT NOT NULL,
  updated_at  BIGINT NOT NULL,
  attachments TEXT
);
CREATE INDEX IF NOT EXISTS idx_requests_domain ON requests(domain, votes DESC, created_at DESC);
CREATE TABLE IF NOT EXISTS request_messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id  BIGINT NOT NULL,
  role        TEXT   NOT NULL,
  author_name TEXT,
  body        TEXT   NOT NULL,
  attachments TEXT,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_request_messages ON request_messages(request_id, created_at);
